Ray Training stderr: (RolloutWorker pid=46404) INFO:services.marl_framework:MARL Framework initialized
(RolloutWorker pid=46404) INFO:services.ray_full_integration:BioInspiredMultiAgentEnv initialized with 30 agents

Ray Training stderr: (RolloutWorker pid=46404) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=46404, ip=172.23.15.241, actor_id=3028570c617c94240426682101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ba428f53e10>)
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/core/models/specs/specs_dict.py", line 123, in validate
(RolloutWorker pid=46404)     raise ValueError(
(RolloutWorker pid=46404) ValueError: The data dict does not match the model specs. Keys ('action_dist',) are in the spec dict but not on the data dict. Data keys are {('action_dist_inputs',)}
(RolloutWorker pid=46404)  [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RolloutWorker pid=46404) During handling of the above exception, another exception occurred:
(RolloutWorker pid=46404) ray::RolloutWorker.__init__() (pid=46404, ip=172.23.15.241, actor_id=3028570c617c94240426682101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7ba428f53e10>)
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [repeated 3x across cluster]
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 64, in __init__ [repeated 2x across cluster]
(RolloutWorker pid=46404)     self._update_policy_map(policy_dict=self.policy_dict)
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1746, in _update_policy_map
(RolloutWorker pid=46404)     self._build_policy_map(
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1857, in _build_policy_map
(RolloutWorker pid=46404)     new_policy = create_policy_for_framework(
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [repeated 2x across cluster]
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/utils/policy.py", line 141, in create_policy_for_framework
(RolloutWorker pid=46404)     return policy_class(observation_space, action_space, merged_config)
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=46404)     self._initialize_loss_from_dummy_batch()
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/policy/policy.py", line 1430, in _initialize_loss_from_dummy_batch
(RolloutWorker pid=46404)     actions, state_outs, extra_outs = self.compute_actions_from_input_dict(
(RolloutWorker pid=46404)                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/policy/torch_policy_v2.py", line 552, in compute_actions_from_input_dict
(RolloutWorker pid=46404)     return self._compute_action_helper(
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/core/models/specs/checker.py", line 371, in wrapper [repeated 4x across cluster]
(RolloutWorker pid=46404)     return func(self, *a, **k)
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^

Ray Training stderr: (RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1208, in _compute_action_helper
(RolloutWorker pid=46404)     fwd_out = self.model.forward_exploration(input_dict)
(RolloutWorker pid=46404)               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=46404)     raise e
(RolloutWorker pid=46404)     return func(self, input_data, **kwargs)
(RolloutWorker pid=46404)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RolloutWorker pid=46404)     _validate(
(RolloutWorker pid=46404)   File "/home/micha/EmergentProtocolFramework/.venv/lib/python3.11/site-packages/ray/rllib/core/models/specs/checker.py", line 162, in _validate
(RolloutWorker pid=46404)     raise SpecCheckingError(
(RolloutWorker pid=46404) ray.rllib.core.models.specs.checker.SpecCheckingError: output spec validation failed on BioInspiredRLModule.forward_exploration, The data dict does not match the model specs. Keys ('action_dist',) are in the spec dict but not on the data dict. Data keys are {('action_dist_inputs',)}